version: '3'

services:
  ca-base:
    image: hyperledger/fabric-ca:${IMAGE_TAG}
    restart: always
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.${ORG_0_HOST}
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.${ORG_0_HOST}-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${CA_KEY}
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.${ORG_0_HOST}-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${CA_KEY} -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/${ORG_0_HOST}/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.${ORG_0_HOST}
    # hostname: ca.${ORG_0_HOST}

networks:
  default:
    external:
      name: nvxclouds.com
