version: '2'
services:
  peer-base:
    image: hyperledger/fabric-peer:${IMAGE_TAG}
    restart: always
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${NETWORKMODE}
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    extra_hosts:
      - "${ORDERER_0_HOST}:${IP_0}"
      - "${ORDERER_1_HOST}:${IP_1}"
      - "${ORDERER_2_HOST}:${IP_2}"
      - "${ORDERER_3_HOST}:${IP_3}"
      - "${ORDERER_4_HOST}:${IP_4}"
      - "peer0.${AU_HOST}:${IP_0}"
      - "peer1.${AU_HOST}:${IP_4}"
      - "peer0.${DP_HOST}:${IP_1}"
      - "peer1.${DP_HOST}:${IP_0}"
      - "peer0.${DU_HOST}:${IP_2}"
      - "peer1.${DU_HOST}:${IP_1}"
      - "peer0.${RL_HOST}:${IP_3}"
      - "peer1.${RL_HOST}:${IP_2}"
      - "peer0.${AP_HOST}:${IP_4}"
      - "peer1.${AP_HOST}:${IP_3}"
       
#    depends_on:
#      - couchdb
#
#  couchdb:
#    container_name: couchdb
#    image: hyperledger/fabric-couchdb
#    environment:
#      - COUCHDB_USER=
#      - COUCHDB_PASSWORD=
#    ports:
#      - 5984:5984